"use client"

import { toast } from "sonner"
import { Download, FileDown, Copy, Check } from "lucide-react"
import { useState } from "react"

interface DownloadSummaryProps {
  title: string
  content: string
}

export function DownloadSummary({ title, content }: DownloadSummaryProps) {
  const [copied, setCopied] = useState(false)
  const [showDropdown, setShowDropdown] = useState(false)

  const safeFileName = title.replace(/[^a-z0-9]/gi, '_').toLowerCase()

  const downloadAsText = () => {
    try {
      const formatted = `Title: ${title}\nGenerated by: PaperSight AI\nDate: ${new Date().toLocaleDateString()}\n${'─'.repeat(40)}\n\n${content}`
      downloadBlob(formatted, `${safeFileName}_summary.txt`, 'text/plain')
      toast.success("Downloaded as TXT")
    } catch {
      toast.error("Download Failed")
    }
    setShowDropdown(false)
  }

  const downloadAsMarkdown = () => {
    try {
      const formatted = `# ${title}\n\n> Generated by [PaperSight AI](https://papersight.ai) on ${new Date().toLocaleDateString()}\n\n---\n\n${content}`
      downloadBlob(formatted, `${safeFileName}_summary.md`, 'text/markdown')
      toast.success("Downloaded as Markdown")
    } catch {
      toast.error("Download Failed")
    }
    setShowDropdown(false)
  }

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(content)
      setCopied(true)
      toast.success("Copied to clipboard")
      setTimeout(() => setCopied(false), 2000)
    } catch {
      toast.error("Failed to copy")
    }
  }

  return (
    <div className="flex gap-2">
      {/* Copy Button */}
      <button
        onClick={copyToClipboard}
        className="px-4 py-2.5 rounded-xl bg-secondary text-foreground hover:bg-accent/20 hover:text-accent border border-border hover:border-accent/30 transition-all duration-200 flex items-center justify-center font-medium text-sm gap-2 hover:scale-[1.02]"
      >
        {copied ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
        {copied ? "Copied!" : "Copy"}
      </button>

      {/* Download Dropdown */}
      <div className="relative">
        <button
          onClick={() => setShowDropdown(!showDropdown)}
          onBlur={() => setTimeout(() => setShowDropdown(false), 150)}
          className="px-4 py-2.5 rounded-xl bg-secondary text-foreground hover:bg-accent/20 hover:text-accent border border-border hover:border-accent/30 transition-all duration-200 flex items-center justify-center font-medium text-sm gap-2 hover:scale-[1.02]"
        >
          <Download className="h-4 w-4" />
          Download
        </button>

        {showDropdown && (
          <div className="absolute right-0 top-full mt-1 w-44 rounded-lg border border-border bg-card shadow-lg z-50 overflow-hidden">
            <button
              onMouseDown={(e) => e.preventDefault()}
              onClick={downloadAsText}
              className="w-full flex items-center gap-2 px-4 py-2.5 text-sm text-foreground hover:bg-accent/10 transition-colors"
            >
              <FileDown className="h-4 w-4 text-muted-foreground" />
              Plain Text (.txt)
            </button>
            <button
              onMouseDown={(e) => e.preventDefault()}
              onClick={downloadAsMarkdown}
              className="w-full flex items-center gap-2 px-4 py-2.5 text-sm text-foreground hover:bg-accent/10 transition-colors"
            >
              <FileDown className="h-4 w-4 text-muted-foreground" />
              Markdown (.md)
            </button>
          </div>
        )}
      </div>
    </div>
  )
}

function downloadBlob(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}