"use client"

import { toast } from "sonner"
import { Download } from "lucide-react"

interface DownloadSummaryProps {
  title: string
  content: string
}

export function DownloadSummary({ title, content }: DownloadSummaryProps) {
  const handleDownload = () => {
    try {
      // Format the content with title and metadata
      const formattedContent = `Title: ${title}
Generated by: PaperSight AI
Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}
----------------------------------------

${content}`

      // Create blob from formatted content
      const blob = new Blob([formattedContent], { type: 'text/plain' })

      // Create temporary link element
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_summary.txt`

      // Trigger download
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)

      toast.success("Download Complete", {
        description: "Summary has been saved to your device."
      })
    } catch {
      toast.error("Download Failed", {
        description: "Unable to generate download file. Please try again."
      })
    }
  }

  return (
    <button
      onClick={handleDownload}
      className="px-4 py-2.5 rounded-xl bg-secondary text-foreground hover:bg-accent/20 hover:text-accent border border-border hover:border-accent/30 transition-all duration-200 flex items-center justify-center font-medium text-sm gap-2 hover:scale-[1.02]"
    >
      <Download className="h-4 w-4" />
      Download Summary
    </button>
  )
}